//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.model.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyboard : Peripherals
    {
        public string KeyTechnology { get; set; }
        public string KeyForm { get; set; }
    }
}
