//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer : Product
    {
        public string Producer { get; set; }
        public string Type { get; set; }
        public string Processor { get; set; }
        public string Ram { get; set; }
        public string HardDrive { get; set; }
        public string OpticalDrive { get; set; }
        public string GraphicsCard { get; set; }
    }
}
