//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerShopContext : DbContext
    {
        public ComputerShopContext()
            : base("name=ComputerShopContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Order> order { get; set; }
        public virtual DbSet<Photo> photo { get; set; }
        public virtual DbSet<Product> product { get; set; }
        public virtual DbSet<Supply> supply { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<DeliveredToWareHouse> DeliveredToWareHouse { get; set; }
        public virtual DbSet<Ordered> Ordered { get; set; }
    }
}
